### ISSUE TITLE
I'm getting the "Game uses an unsupported Resolution" error. I tried changing the resolution of the game. but the error is the same

### ISSUE THREAD

**Issue by royyo** [Bappsack/OwO-Maker#1]
I'm getting the "Game uses an unsupported Resolution" error. I tried changing the resolution of the game. but the error is the same

**Comment by Bappsack** [comment]
Sounds like you are either using a Custom Resolution wich is not provided by the Game itself or your machine struggles to get the resolution of the Window (permissions?, Admin rights?)

**Comment by royyo** [comment]
what can i do, im do only in game settings resolution 1024x768, 1280x1024, 1280x800,1024x700 etc.

**Comment by Bappsack** [comment]
start the application with Admin Permissions.

**Comment by royyo** [comment]
I already do that

**Comment by Bappsack** [comment]
Give me more informations then.

Official Gameforge Server?
What Server?
Windows Version?

**Comment by royyo** [comment]
Windows 11 pro , official gameforge eu dragonveil server

**Comment by Bappsack** [comment]
does your Title of the game even Change? like this:
![image](https://github.com/user-attachments/assets/753c1269-7a9c-43de-98a0-8b95d2555a9a)

**Comment by royyo** [comment]
yeah same 
![image](https://github.com/user-attachments/assets/e861c187-bce3-43b1-a902-716099befb21)

**Comment by Bappsack** [comment]
then something is blocking the winapi call GetClientRect. try disabling your antivirus maybe?

**Comment by royyo** [comment]
Unfortunately this didn't work either, I guess I'm cursed but this error (0x0)
![image](https://github.com/user-attachments/assets/a015f95b-0e9f-444e-844b-afc22eb577c8)

**Comment by Bappsack** [comment]
0x0 is the returning Resolution, wich is empty. Can't help you out if your system is blocking the Call.

**Comment by royyo** [comment]
How can I fix the system blocking?

**Comment by Bappsack** [comment]
i don't know what is blocking it on your system. before i released it i tested both Windows 10 and 11 in a fresh Virtual machine and both worked fine.

i asume your game is in english?

**Comment by royyo** [comment]
No my game is Turkish i will change and try again

**Comment by royyo** [comment]
![image](https://github.com/user-attachments/assets/37432262-1d4c-4f5f-b67c-14cc1bceee7d)
unfortunately it's still the same. I'm sorry for bothering you. thanks

**Comment by Bappsack** [comment]
but you are now getting a resolution somehow, i changed my language to turkish and it still works fine.

however, 1024x640 is not a resolution the game provides.
